### ISSUE TITLE
Is this abandoned? 

### ISSUE THREAD

**Issue by seivan** [cocos2d/cocos2d-x-swift-bindings#1]
I was thinking of doing an update to Swift 2 -> and also adding more support for the Cocos2d stuff like Components and Map/Vector.

**Comment by mannewalis** [comment]
Not abandoned. Parked for now, awaiting open sourcing of the Swift language.

**Comment by seivan** [comment]
It actually sounds like a good project, I was hoping to add some of the stuff that's missing (like cocos2d::Component).

But, isn't it easier to just use Cocos2d-objc?

**Comment by mannewalis** [comment]
Cocos2d is not cross platform and only targets iOS. Cocos2d-x targets many platforms, so these bindings are for Cocos2d-x.

**Comment by seivan** [comment]
Yeah I figured that, but since Swift is going Open Source, doesn't it mean the rendering in Cocos2d could go for the same platforms as Swift?
I mean you can already run Obj-C on Windows. Look at Microsofts recent work: https://github.com/Microsoft/WinObjC

**Comment by mannewalis** [comment]
Yeah possibly. I think the effort is going into Cocos2d-x at this point, so although there will be some support for Cocos2d, I think that the focus is not going to be there.

See. http://forum.cocos2d-objc.org/t/the-future-of-cocos2d-objc/17549

**Comment by mannewalis** [comment]
I will add though, that if you can have swift bindings for cocos2d-x, then you automatically have objc bindings as well, so you will be able to pick at that point.

**Comment by seivan** [comment]
I am bringing this up because Cocos2d-objc has LightNode, Blurs and other effects.
I am not sure what to pick to go with :-/ I _know_ Swift will run on Windows and Linux soon, and I can be sure that Cocos2d will follow. 

So.. not sure what to pick as of now...

**Comment by mannewalis** [comment]
yeah, I guess it depends on your target, and when you want to be done by. I think it will be at least 6 months before swift shows up for android, but it may be available for windows before that. I haven't been paying too much attention to it, so I'm sorry I can't be more helpful.

**Comment by seivan** [comment]
No worries :) Thanks for helping!
